; PlatformIO project configuration for ESP32-C3 Mini SML Optical Meter Reader
; Board: ESP32-C3 Mini
; Platform: Espressif ESP32 (ESP-IDF framework)
;;
;Hauptanschluss / interner IR-Lesekopf: GPIO3 (RX) / GPIO1 (TX)
;Uart/RS458 converter fro SMD72 GPIO20 (RX) / 1 (TX), 

[platformio]
default_envs = esp32c3_optical_meter
src_dir = src/app

; ============================================================
; Common settings shared across environments
; ============================================================
[env]
platform = espressif32
framework = espidf
extra_scripts = pre:version_increment.py

build_flags =
    -DESP_PLATFORM
    -std=gnu++17
    -Wall
    -Wextra
    -Wno-unused-parameter

; ============================================================
; Production: ESP32-C3 Mini optical meter reader
; ============================================================
[env:esp32c3_optical_meter]
board = lolin_c3_mini

upload_speed  = 115200
monitor_speed = 115200
monitor_filters =
    colorize
    time

build_flags =
    ${env.build_flags}

; Partition table
board_build.partitions = partitions_4mb_ota.csv


